src/Entity/Illustration.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\IllustrationRepository")
 */
class Illustration
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ill_titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $ill_contenu;

    /**
     * @ORM\Column(type="datetime")
     */
    private $ill_date_creation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Image", inversedBy="illustration",cascade={"persist", "remove" })
     */
    private $images;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Utilisateur", inversedBy="utiIllustrations")
     */
    private $utilisateurs;

    /**
     * @ORM\Column(type="datetime")
     */
    private $derniere_modification;

    public function __construct()
    {
        $this->ill_date_creation=new \DateTime('now',new \DateTimeZone('Europe/Paris'));
        $this->utilisateurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIllTitre(): ?string
    {
        return $this->ill_titre;
    }

    public function setIllTitre(string $ill_titre): self
    {
        $this->ill_titre = $ill_titre;

        return $this;
    }

    public function getIllContenu(): ?string
    {
        return $this->ill_contenu;
    }

    public function setIllContenu(?string $ill_contenu): self
    {
        $this->ill_contenu = $ill_contenu;

        return $this;
    }

    public function getIllDateCreation(): String
    {
        $date="Pas de date de rentrée";
        if($this->ill_date_creation!=null)
        {
            $date=$this->getFormattedDate();
        }
        return $date;
    }

    public function setIllDateCreation(\DateTimeInterface $ill_date_creation): self
    {
        $this->ill_date_creation = $ill_date_creation;

        return $this;
    }

    /**
     * @return Collection|image[]
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * @param UploadedFile $file
     * @return $this
     * @throws \Exception
     */
    public function addImage(?File $file): self
    {
        $image = new Image();
        $image->setImaFichier($file);
        $image->addIllustration($this);
        $this->images=$image;
        if($file instanceof UploadedFile)
        {
            $this->derniere_modification = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @param UploadedFile $file
     * @return $this
     */
    public function removeImage(UploadedFile $file): self
    {
        $image = new Image();
        $image->setImaFichier($file);
        if($this->images==$image)
        {
            $this->$image=null;
        }
        return $this;
    }

    /**
     * @return ArrayCollection|null
     */
    public function getUtilisateur()
    {
        return $this->utilisateurs;
    }

    public function addUtilisateur(?Utilisateur $utilisateur): self
    {
        if(!$this->utilisateurs->contains($utilisateur))
        {
            $this->utilisateurs[] = $utilisateur;
            $utilisateur->addUtiIllustration($this);
        }
        return $this;
    }
    public function getFormattedDate(): ?string
    {
        setlocale(LC_TIME, ['fr', 'fra', 'fr_FR']);
        return strftime("%d %B %G",$this->ill_date_creation->getTimestamp());
    }

    public function getDerniereModification(): ?\DateTimeInterface
    {
        return $this->derniere_modification;
    }

    public function setDerniereModification(\DateTimeInterface $derniere_modification): self
    {
        $this->derniere_modification = $derniere_modification;

        return $this;
    }
}

src/Form/Illustration/IllustrationSearchType.php
<?php
namespace App\Form\Illustration;

use App\Entity\IllustrationSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IllustrationSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre', TextType::class, [
                    'required' => false,
                    'label' => false,
                    'attr' => [
                        'placeholder' => "Ill titre",
                        'class' => 'autocomplete',
                        'autocomplete' => "off"
                    ]
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => IllustrationSearch::class,
            'method' => 'get',
            'csrf_protection' => false,
            'translation_domain' => 'Illustration_form'
        ]);
    }

    public function getBlockPrefix()
    {
        return "";
    }
}

src/Form/Illustration/IllustrationType.php
<?php


namespace App\Form\Illustration;


use App\Entity\Illustration;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IllustrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('illTitre', TextType::class,[
                'required' => true,
                'label' => 'Titre'
            ])
            ->add('illContenu', CKEditorType::class, [
                'label' => false,
                'config' => [
                    'config_name' => 'basic_config',
                ]
            ])
            ->add('images', FileType::class, [
                    'required'=> false,
                    'multiple' => true,
                    'attr'     => [
                        'accept' => 'image/*',
                        'multiple' => 'multiple',
                        'placeholder' => 'choisir une image'
                    ]
                ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Illustration::class,
            'translation_domain' => 'illustration_form' //TODO faire la traduction
        ]);
    }
}

src/Controller/creation/IllustrationController.php
<?php


namespace App\Controller\creation;


use App\Entity\Illustration;
use App\Entity\IllustrationSearch;
use App\Form\Illustration\IllustrationSearchType;
use App\Repository\IllustrationRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class IllustrationController
 * @package App\Controller
 * @Route("/{_locale}/illustration")
 */
class IllustrationController extends AbstractController
{


    private $repository;
    public function __construct(IllustrationRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("", name="illustration.index")
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request,PaginatorInterface $paginator): Response
    {
        $search = new IllustrationSearch();
        $searchForm = $this->createForm(IllustrationSearchType::class,$search);
        $searchForm->handleRequest($request);

        $illustrationPage = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('creation/illustration/illustration_index.html.twig', [
            'current_page' => 'illustration',
            'illustration' => $illustrationPage,
            'searchForm' => $searchForm->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="illustration.show")
     * @param Illustration $illustrations
     * @return Response
     */
    public function show(Illustration $illustrations): Response {
        return $this->render('creation/illustration/illustration_post.html.twig', [
            'current_page' => 'illustration',
            'illu' => $illustrations
        ]);
    }

}

src/Controller/creation/MangaController.php
<?php


namespace App\Controller\creation;


use App\Entity\Illustration;
use App\Entity\Manga;
use App\Entity\MangaSearch;
use App\Entity\NewsSearch;
use App\Form\manga\MangaSearchType;
use App\Repository\MangaRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class MangaController
 * @package App\Controller
 * @Route("/{_locale}/manga")
 */
class MangaController extends AbstractController
{
    private $repository;
    public function __construct(MangaRepository $repository)
    {
        $this->repository = $repository;
    }
    /**
     * @Route("", name="manga.index")
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request,PaginatorInterface $paginator): Response
    {
        $search = new MangaSearch();
        $searchForm = $this->createForm(MangaSearchType::class,$search);
        $searchForm->handleRequest($request);
        $mangaPage = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('creation/manga/manga_index.html.twig', [
            'current_page' => 'illustration',
            'manga' => $mangaPage,
            'searchForm' => $searchForm->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="manga.show")
     * @param Manga $manga
     * @return Response
     */
    public function show(Manga $manga) : Response {
        return $this->render('creation/manga/manga_post.html.twig', [
            'current_page' => 'manga',
            'manga' => $manga
        ]);
    }
}

src/Controller/creation/RecruitmentController.php
<?php


namespace App\Controller\creation;


use App\Entity\Candidature;
use App\Entity\Recrutement;
use App\Form\Recruitment\ApplicationEditType;
use App\Repository\RecrutementRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class RecruitmentController
 * @package App\Controller
 * @Route("/{_locale}/recruitment")
 */
class RecruitmentController extends AbstractController
{

    /**
     * @var RecrutementRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $manager;

    public function __construct(RecrutementRepository $repository, ObjectManager $manager)
    {
        $this->repository = $repository;
        $this->manager = $manager;
    }

    /**
     * @Route("", name="recruitment.index")
     * @return Response
     * @throws \Exception
     */
    public function index(): Response
    {

        return $this->render('creation/recruitment/recruitment_index.html.twig', [
            'current_page' => 'recruitment',
            'officialJobs' => $this->repository->findOfficialJobs(),
            'otherJobs' => $this->repository->findOtherJobs()
        ]);
    }

    /**
     * @Route("/{slug}-{id}", name="recruitment.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Recrutement $recrutement
     * @param Request $request
     * @return Response
     */
    public function show(Recrutement $recrutement, string $slug, Request $request): Response
    {
        if ($recrutement->getSlug() !== $slug)
            return $this->redirectToRoute('admin.roles.show', [
                'id' => $recrutement->getId(),
                'slug' => $recrutement->getSlug()
            ], 301);

        return $this->render('creation/recruitment/recruitment_show.html.twig', [
            'current_page' => 'recruitment_show',
            'job' => $recrutement,
        ]);
    }


    /**
     * @Route("/{slug}-{id}/apply", name="recruitment.apply", requirements={"slug": "[a-z0-9\-]*"})
     * IsGranted("ROLE_USER_APPLY")
     * @param Recrutement $recrutement
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function apply(Recrutement $recrutement, string $slug, Request $request): Response
    {
        if ($recrutement->getSlug() !== $slug)
            return $this->redirectToRoute('admin.roles.show', [
                'id' => $recrutement->getId(),
                'slug' => $recrutement->getSlug()
            ], 301);


        $candidature = new Candidature();
        $candidature->setUtilisateur($this->getUser());
        $candidature->setRecrutement($recrutement);
        $candidature->setCanDate(new \DateTime());

        $form = $this->createForm(ApplicationEditType::class, $candidature);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $candidature->setCanEtat('New');
                $this->manager->persist($recrutement);
                $this->manager->flush();
                $this->addFlash('notif', 'Candidature créée avec succès !');
            } else
                $this->addFlash('notif', 'Impossible de créer cette candidature.');
        }

        if ($form->isSubmitted() && $form->isValid())
            return $this->redirectToRoute('users.show', ['id' => $this->getUser()->getId()]);

        return $this->render('creation/recruitment/recruitment_apply.html.twig', [
            'current_page' => 'recruitment_apply',
            'job' => $recrutement,
            'form' => $form->createView()
        ]);
    }

}

src/Controller/creation/ScenarioController.php
<?php


namespace App\Controller\creation;


use App\Entity\NewsSearch;
use App\Entity\Scenario;
use App\Entity\ScenarioSearch;
use App\Form\News\NewsSearchType;
use App\Form\Scenario\ScenarioSearchType;
use App\Repository\PublicationRepository;
use App\Repository\ScenarioRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ScenarioController
 * @package App\Controller
 * @Route("/{_locale}/scenario")
 */
class ScenarioController extends AbstractController
{
    private $repository;
    public function __construct(ScenarioRepository $repository)
    {
        $this->repository = $repository;
    }
    /**
     * @Route("", name="scenario.index")
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request,PaginatorInterface $paginator): Response
    {
        $search = new ScenarioSearch();
        $searchForm = $this->createForm(ScenarioSearchType::class,$search);
        $searchForm->handleRequest($request);

        $scenarioPage = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('creation/scenario/scenario_index.html.twig', [
            'current_page' => 'scenario',
            'scenario' => $scenarioPage,
            'searchForm' => $searchForm->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="scenario.show")
     * @param Scenario $scenario
     * @return Response
     */
    public function show(Scenario $scenario): Response
    {
        return $this->render('creation/scenario/scenario_post.html.twig', [
            'current_page' => 'scenario',
            'scenario' => $scenario
        ]);
    }

}

templates/creation/illustration/illustration_index.html.twig
{% extends 'base.html.twig' %}
{% block title 'LeMangaFrancais | Illustrations' %}
{% block body %}
    <div class="grey lighten-4 center">
        <h1>Les illustrations</h1>
        <h6>Retrouvez les dernières Illustrations publiées</h6>
        <div class="row">
            <div class="col l7 offset-l1">
                <div class="section left-align">
                    <h5>Dernières Illustrations</h5>
                    <div class="divider"></div>
                </div>
                {% for page in illustration %}
                <div class="col l6 left-align">
                    <a href="{{ path('illustration.show', { id: page.id}) }}">
                        <div class="card hoverable waves-effect waves-block waves-blue" style="height: 500px;">
                            <div class="card-image">
                                <img src="{{ page.images.ImaNomFichier ? vich_uploader_asset(page.images, 'ima_fichier') : "/media/illustrations/default.png" | imagine_filter('illustration_index') }}" alt="Image Article" style="width:100%; height: 250px">
                            </div>
                            <div class="card-content">
                                <div class="chip blue white-text">{{ page.IllDateCreation|title }}</div>
                                <span class="span card-title">{{ page.IllTitre }}<br>par
                                    {% for utilisateur in page.utilisateur %}
                                        <span class="orange-text">{{ utilisateur.id }}</span>
                                    {% endfor %}
                                </span>
                                <p style="word-break: break-word;">{{ page.IllContenu|truncate(300,false,"...")|raw }}</p>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/creation/illustration/illustration_post.html.twig
{% extends 'base.html.twig' %}

{% block title 'LeMangaFrancais | Scénarios' %}

{% block body %}
    <div class="grey lighten-4 center">
        <h1></h1>
        <div class="row">
            <div class="col l7 offset-l1">
                <div class="section left-align">
                    <h4><b>{{ illu.illTitre }}</b></h4>
                    <div class="divider"></div>
                </div>
                <div class="white z-depth-3 rounded section big-margin-bottom">
                    <img src="{{ illu.images.ImaNomFichier ? vich_uploader_asset(illu.images, 'ima_fichier') : "/media/illustrations/default.png" | imagine_filter('illustration_page') }}" alt="Image Article" class=" margin-top margin-bottom z-depth-3" style=" height: 85%; width: 85%;">
                </div>
            </div>
            <div class="col l3">
                <div class="section left-align">
                    <h4 class="left-align">Informations</h4>
                    <div class="divider"></div>
                </div>
                <div class="white z-depth-3 rounded section margin-bottom">
                    <h4>Auteur</h4>
                    <div class="divider"></div>
                    {% for utilisateur in illu.utilisateur %}
                        <h5></h5>
                        <img src="{{utilisateur.utiAvatarNomFichier ? vich_uploader_asset(app.user, 'utiAvatarFichier') : "/media/users/avatar/default.jpg" | imagine_filter('avatarsmall') }}" alt="" class="circle" style="width: 150px; height: 150px">
                        <h5><b>{{ utilisateur.id }}</b></h5>
                        {% for role in utilisateur.utiroles %}
                            <span class="grey-text">{{ role.rolNom }}</span>
                        {% endfor %}
                        <p class="margin-right margin-left"><b>Biographie :</b><br>{{ utilisateur.UtiBiographie }}</p>
                        <div class="divider"></div>
                    {% endfor %}
                    <p><b>Date de publication : </b>{{ illu.illDateCreation }}<br>
                        <b>Pages : </b>3 <br>
                        <b>Type : </b>Soupe <br>
                    </p>
                    <p><b>Tags : </b>Horreur / Fantaisie</p>
                </div>
                <div class="white z-depth-3 rounded section margin-bottom">
                    <h4>Description</h4>
                    <div class="divider"></div>
                    <p>{{ illu.illContenu | raw }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}