src/Entity/Lexique.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LexiqueRepository")
 */
class Lexique
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $LexMot;

    /**
     * @ORM\Column(type="text")
     */
    private $LexDefinition;

    private $slug;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLexMot(): ?string
    {
        return $this->LexMot;
    }

    public function setLexMot(string $LexMot): self
    {
        $this->LexMot = $LexMot;

        return $this;
    }

    public function getLexDefinition(): ?string
    {
        return $this->LexDefinition;
    }

    public function setLexDefinition(string $LexDefinition): self
    {
        $this->LexDefinition = $LexDefinition;

        return $this;
    }
    public function getSlug() : string
    {
        return isset($this->slug) ? $this->slug : $this->slug = (new Slugify())->slugify($this->LexMot);
    }
}

src/Form/Lexicon/LexiqueSearchType.php
<?php

namespace App\Form\Lexicon;

use App\Entity\LexiqueSearch;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LexiqueSearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mot', TextType::class, [
                'required' => false,
                'label' => 'Mot',
                'attr' => [
                    'placeholder' => 'Chercher un mot',
                    'class' => 'autocomplete center'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => LexiqueSearch::class,
            'method' => 'GET',
            'csrf_protection' => false,
            'translation_domain' => 'lexique_form'

        ]);
    }

    public function getBlockPrefix()
    {
        return '';
    }

}

src/Controller/lexicon/LexiconController.php
<?php


namespace App\Controller\lexicon;


use App\Entity\LexiqueSearch;
use App\Form\Lexicon\LexiqueSearchType;
use App\Repository\LexiqueRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class LexiconController
 * @package App\Controller
 * @Route("/{_locale}/lexicon")
 */
class LexiconController extends AbstractController
{
    private $repository;
     public function __construct(LexiqueRepository $Repository)
    {
        $this->repository= $Repository;
    }

    /**
     * @Route("", name="lexicon.index")
     *
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function index(Request $request,PaginatorInterface $paginator): Response
    {
        $search = new LexiqueSearch();
        $searchForm = $this->createForm(LexiqueSearchType::class,$search);
        $searchForm->handleRequest($request);

        $lexiquePage = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('lexicon/lexicon_index.html.twig', [
            'current_page' => 'lexicon',
            'pageLexicons' => $lexiquePage,
            'searchForm' => $searchForm->createView()
        ]);
    }

}

templates/lexicon/lexicon_index.html.twig
{% extends 'base.html.twig' %}
{% block title 'LeMangaFrancais | Lexicon' %}
{% block body %}
    <div class="row">
        <div class="col s1"></div>
        <div class=" col s10">
            <div>
                {{ form_start(searchForm) }}
                <button class="hiddendiv"></button>
                {{ form_end(searchForm) }}
            </div>
            <table class="striped #bbdefb blue lighten-4 ronded">
                <thead>
                <th><div class="centered" style="white-space: nowrap">{{ knp_pagination_sortable(pageLexicons, 'Nom', 'l.LexMot') }}</div></th>
                <th><div class="centered">{{ knp_pagination_sortable(pageLexicons, 'Defintion', 'l.LexDefinition') }}</div></th>
                </thead>
                <tbody>
                {% for mot in pageLexicons %}
                    <tr>
                        <td style="width: 25%; white-space: nowrap">{{ mot.lexMot }}</td>
                        <td style="width: 75%; text-align: justify">{{ mot.lexDefinition }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div>{{ knp_pagination_render(pageLexicons) }}</div>
        </div>

        <div class="col s1"></div>
    </div>
{% endblock %}