src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use Serializable;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Utilisateur
 *
 * @ORM\Entity(repositoryClass="App\Repository\UtilisateurRepository")
 * @Vich\Uploadable
 */
class Utilisateur implements UserInterface, Serializable
{
    /**
     * @var string
     *
     * @ORM\Column(type="string", length=40, nullable=false, unique=true)
     * @Assert\Length(min=3)
     * @ORM\Id()
     */
    private $id;

    /**
     * @var int|null
     *
     * @ORM\Column(type="string", length=36, nullable=true)
     */
    private $utiIdParrainer;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", inversedBy="utilisateurs")
     * @ORM\JoinTable(name="endosser")
     */
    private $utiRoles;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Scenario", inversedBy="utilisateurs")
     */
    private $utiScenarios;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=false)
     */
    private $lanId;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100, nullable=false)
     * @Assert\Email()
     */
    private $utiMail;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=12, nullable=true)
     * @Assert\Length(min=10, max=12)
     */
    private $utiTelephone;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="date", nullable=true)
     */
    private $utiNaissance;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $utiInscription;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $utiDerniereSession;

    /**
     * @var bool|null
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $utiConnecte;

    /**
     * @var File|null
     *
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="users_avatar_image", fileNameProperty="utiAvatarNomFichier")
     */
    private $utiAvatarFichier;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $utiAvatarNomFichier;

    /**
     * @var int|null
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $utiTokens;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=300, nullable=true)
     */
    private $utiBiographie;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=300, nullable=false)
     */
    private $utiMdp;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $utiIp;

    /**
     * @var int|null
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    private $utiNotif;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $utiDerniereMAJ;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Activites", mappedBy="actUtilisateur", orphanRemoval=true)
     */
    private $utiActivites;

    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="App\Entity\News", mappedBy="utilisateurs")
     */
    private $utiNews;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Recrutement", mappedBy="utilisateur")
     */
    private $recrutements;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Candidature", mappedBy="utilisateur", orphanRemoval=true)
     */
    private $candidatures;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Manga", mappedBy="utilisateurs")
     */
    private $utiMangas;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Illustration", mappedBy="utilisateurs")
     */
    private $utiIllustrations;


    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Ticket", mappedBy="utilisateur")
     */
    private $utiTickets;


    /**
     * @return ArrayCollection
     */
    public function getUtiTickets(): ArrayCollection
    {
        return $this->utiTickets;
    }


    public function __construct()
    {
        $this->lanId = 1;
        $this->utiInscription = $this->utiDerniereMAJ = new \DateTime();
        $this->utiRoles = new ArrayCollection();
        $this->utiActivites = new ArrayCollection();
        $this->utiNews = new ArrayCollection();
        $this->recrutements = new ArrayCollection();
        $this->candidatures = new ArrayCollection();
        $this->utiScenarios = new ArrayCollection();
        $this->utiMangas = new ArrayCollection();
        $this->utiIllustrations = new ArrayCollection();
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @param Illustration|null $illustration
     * @return $this
     */
    public function addUtiIllustration(?Illustration $illustration): self
    {
        if(!$this->utiIllustrations->contains($illustration))
        {
            $this->utiIllustrations[] = $illustration;
        }
        return $this;
    }

    /**
     * @return ArrayCollection|null
     */
    public function getUtiIllustration()
    {
        return $this->utiIllustrations;
    }

    public function getUtiManga()
    {
        return $this->utiMangas;
    }

    /**
     * @param Manga|null $manga
     * @return $this
     */
    public function addUtiManga(?Manga $manga): self
    {
        if(!$this->utiMangas->contains($manga))
        {
            $this->utiMangas[] = $manga;
        }
        return $this;
    }

    /**
     * @return ArrayCollection|null
     */
    public function getUtiScenario()
    {
        return $this->utiScenarios;
    }

    /**
     * @param Scenario $scenario
     * @return $this
     */
    public function addUtiScenario(Scenario $scenario): self
    {
        if(!$this->utiScenarios->contains($scenario))
        {
            $this->utiScenarios[] = $scenario;
        }
        return $this;
    }

    public function getUtiIdParrainer(): ?int
    {
        return $this->utiIdParrainer;
    }

    public function setUtiIdParrainer(?int $utiIdParrainer): self
    {
        $this->utiIdParrainer = $utiIdParrainer;

        return $this;
    }

    public function getLanId(): ?int
    {
        return $this->lanId;
    }

    public function setLanId(int $lanId): self
    {
        $this->lanId = $lanId;

        return $this;
    }

    public function getUtiMail(): ?string
    {
        return $this->utiMail;
    }

    public function setUtiMail(?string $utiMail): self
    {
        $this->utiMail = $utiMail;

        return $this;
    }

    public function getUtiTelephone(): ?string
    {
        return $this->utiTelephone;
    }

    public function setUtiTelephone(?string $utiTelephone): self
    {
        $this->utiTelephone = $utiTelephone;

        return $this;
    }

    public function getUtiNaissance(): ?\DateTimeInterface
    {
        return $this->utiNaissance;
    }

    public function getUtiNaissanceString(): string
    {
        $resultat = 'Aucun';

        if ($this->utiNaissance !== null)
            $resultat = $this->utiNaissance->format('d-m-Y H:i:s');

        return $resultat;
    }

    public function setUtiNaissance(?\DateTimeInterface $utiNaissance): self
    {
        $this->utiNaissance = $utiNaissance;

        return $this;
    }

    public function getUtiInscription(): ?\DateTimeInterface
    {
        return $this->utiInscription;
    }

    public function getUtiInscriptionString(): string
    {
        return $this->utiInscription->format('d-m-Y');
    }

    public function setUtiInscription(?\DateTimeInterface $utiInscription): self
    {
        $this->utiInscription = $utiInscription;

        return $this;
    }

    public function getUtiDerniereSession(): ?\DateTimeInterface
    {
        return $this->utiDerniereSession;
    }

    public function getUtiDerniereSessionString(): string
    {
        $resultat = 'Aucun';

        if ($this->utiDerniereSession !== null)
            $resultat = $this->utiDerniereSession->format('d-m-Y H:i:s');

        return $resultat;
    }

    public function setUtiDerniereSession(?\DateTimeInterface $utiDerniereSession): self
    {
        $this->utiDerniereSession = $utiDerniereSession;

        return $this;
    }

    public function getUtiConnecte(): ?bool
    {
        return $this->utiConnecte;
    }

    public function setUtiConnecte(?bool $utiConnecte): self
    {
        $this->utiConnecte = $utiConnecte;

        return $this;
    }

    public function getUtiTokens(): ?int
    {
        return $this->utiTokens;
    }

    public function setUtiTokens(?int $utiTokens): self
    {
        $this->utiTokens = $utiTokens;

        return $this;
    }

    public function getUtiBiographie(): ?string
    {
        return $this->utiBiographie;
    }

    public function setUtiBiographie(?string $utiBiographie): self
    {
        $this->utiBiographie = $utiBiographie;

        return $this;
    }

    public function getUtiMdp(): ?string
    {
        return $this->utiMdp;
    }

    public function setUtiMdp(?string $utiMdp): self
    {
        $this->utiMdp = $utiMdp;

        return $this;
    }

    public function getUtiIp(): ?string
    {
        return $this->utiIp;
    }

    public function setUtiIp(?string $utiIp): self
    {
        $this->utiIp = $utiIp;

        return $this;
    }

src/Controller/user/UsersIllustrationController.php
<?php


namespace App\Controller\user;


use App\Entity\Illustration;
use App\Entity\Utilisateur;
use App\Form\Illustration\IllustrationType;
use App\Repository\IllustrationRepository;
use App\Repository\ImageRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UsersIllustrationController extends AbstractController
{
    /**
     * @var ObjectManager
     */
    private $manager;

    /**
     * @var IllustrationRepository
     */
    private $illustrationRepository;

    /**
     * @var IllustrationRepository
     */
    private $imageRepository;

    public function __construct(ObjectManager $manager, IllustrationRepository $illustrationRepository, ImageRepository $imageRepository)
    {
        $this->manager = $manager;
        $this->illustrationRepository = $illustrationRepository;
        $this->imageRepository= $illustrationRepository;
    }

    /**
     * @Route("/{id}/indexIllustration", name="usersIllustration.index", methods="GET|POST")
     * @param Utilisateur $utilisateur
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(Utilisateur $utilisateur, PaginatorInterface $paginator, Request $request): Response
    {
        $illustrationPage  = $paginator->paginate(
            $utilisateur->getUtiIllustration(),
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('users/users_show/users_show_creations/users_show_illustration.html.twig',[
            'current_page' => 'index',
            'allIllustration'=> $illustrationPage,
            'user' => $utilisateur
        ]);
    }

    /**
     * @Route("/{id}/addIllustration", name="users.addIllustration", methods="GET|POST")
     * @param Request $request
     * @param Utilisateur $utilisateur
     * @return Response
     */
    public function addIllustration(Request $request, Utilisateur $utilisateur) : Response
    {
        $illustration = new Illustration();
        $form = $this->createForm(IllustrationType::class,$illustration);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $illustration->addUtilisateur($utilisateur);
                $this->addFlash('notif', 'illustration créé avec succès !');
                $this->manager->persist($illustration);
                $this->manager->flush();
                return $this->redirectToRoute("usersIllustration.index",['id'=>$utilisateur->getId()]);
            }
            else
            {
                $this->addFlash('notif', 'Impossible de créer l\'$illustration.');
                return $this->redirectToRoute("usersIllustration.index",['utilisateur'=>$utilisateur->getId()]);
            }
        }
        return $this->render('users/users_show/users_show_creations/users_show_illustration_addform.html.twig',[
            'current_page' => 'illustration_add',
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/editIllustration/{utilisateur}/{illustration}", name="users.editIllustration", methods="GET|POST")
     * @param Request $request
     * @param Utilisateur $utilisateur
     * @param Illustration $illustration
     * @return Response
     */
    public function editIllustration(Request $request, Utilisateur $utilisateur, Illustration $illustration): Response
    {
        $form = $this->createForm(IllustrationType::class,$illustration);
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $this->addFlash('notif', 'illustration créé avec succès !');
                $this->manager->flush();
                return $this->redirectToRoute("usersIllustration.index",['id'=>$utilisateur->getId()]);
            }
            else
            {
                $this->addFlash('notif', 'Impossible de créer l\'$illustration.');
                return $this->redirectToRoute("usersIllustration.index",['utilisateur'=>$utilisateur->getId()]);
            }
        }
        return $this->render('users/users_show/users_show_creations/users_show_illustration_editform.html.twig',[
            'current_page' => 'illustration_edit',
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/deleteIllustration/{utilisateur}/{illustration}", name="users.deleteIllustration", methods="DELETE")
     * @param Request $request
     * @param Utilisateur $utilisateur
     * @param Illustration $illustration
     * @return Response
     */
    public function deleteIllustration(Request $request, Utilisateur $utilisateur, Illustration $illustration): Response
    {
        if ($this->isCsrfTokenValid('delete' . $illustration->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($illustration);
            $entityManager->flush();
            $this->addFlash('notif', 'Illustration supprimé avec succès !');
        }

        return $this->redirectToRoute('usersIllustration.index',["id"=>$utilisateur->getId()]);
    }

}

templates/users/users_show/users_show_activities.html.twig
<div class="container">
    <table class="centered">
        <thead>
        <tr>
            <th>Heure</th>
            <th>Activité</th>
        </tr>
        </thead>
        <tbody>
        {% for activite in user.utiActivites %}
            <tr>
                <td>{{ activite.actDate }}</td>
                <td>{{ activite.actDescription }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

templates/users/users_show/users_show_edit.html.twig
<div class="container">
    <h4 class="center">Mes Posts</h4>
    <div class="container margin-top center">
        <a class="waves-effect waves-light btn" href="{{ path("usersScenario.index", {id:user.id}) }}"><i class="material-icons right">library_books</i>Scenario</a>
        <a class="waves-effect waves-light btn" href="{{ path("usersIllustration.index", {id:user.id}) }}"><i class="material-icons right">insert_photo</i>Illustration</a>
        <a class="waves-effect waves-light btn" href="{{ path("usersManga.index", {id:user.id}) }}"><i class="material-icons right">local_library</i>Manga</a>
    </div>

    {{ form_start(form) }}
    <div class="row">
        <div class="col s12">{{ form_row(form.utiBiographie) }}</div>
    </div>
    <div class="row">
        <div class="col m6 s12">{{ form_row(form.utiMail) }}</div>
        <div class="col m6 s12">{{ form_row(form.utiNaissance) }}</div>
    </div>
    <div class="row">
        <div class="col m6 s12">{{ form_row(form.utiTelephone) }}</div>
        <div class="col m6 s12">{{ form_row(form.utiMdp) }}</div>
    </div>
    {{ form_rest(form) }}
    <div class="row">
        <button class="btn yellow darken-4 waves-effect waves-light col s10 margin-bottom"><i class="material-icons">edit</i> Editer</button>
        {{ form_end(form) }}
        <div class="col s1 offset-s1">
            {{ include('admin/admin_users/admin_users_deleteform.html.twig') }}
        </div>
    </div>
</div>

templates/users/users_show/users_show_index.html.twig
{% extends 'base.html.twig' %}

{% block title 'LeMangaFrancais | Profile' %}

{% block body %}
    <div class="container big-margin-top big-margin-bottom">
        <h5><strong class="grey-text text-lighten-1">PAGE DE PROFIL</strong></h5>
        <div class="white z-depth-3 rounded">
            <div class="center">
                <img height="200" width="200" class="circle z-depth-3" src="{{ user.utiAvatarNomFichier ? vich_uploader_asset(user, 'utiAvatarFichier') : "/media/users/avatar/default.jpg" | imagine_filter('avatarmedium') }}" alt="Image" style="margin-top: -100px">
                <h4 style="color: {{ user.utiRoles[0].rolCouleur }}"><strong>{{ user.id|upper }}</strong></h4>
                <h5 class="grey-text">
                    <strong>
                        {% for role in user.utiRoles %}
                            {{ role.rolNom | upper }}
                        {% endfor %}
                    </strong>
                </h5>
            </div>
            <div class="row">
                <div class="col s12">
                    <ul class="tabs">
                        <li class="tab col s{{ app.user and app.user.id == user.id ? '4' : '6' }}"><a href="#page1">Informations</a></li>
                        <li class="tab col s{{ app.user and app.user.id == user.id ? '4' : '6' }}"><a href="#page2">Activités</a></li>
                        {% if app.user and app.user.id == user.id %}
                            <li class="tab col s4"><a href="#page3">Editer</a></li>
                        {% endif %}
                    </ul>
                    <div id="page1" class="col s12">{{ include('users/users_show/users_show_infos.html.twig') }}</div>
                    <div id="page2" class="col s12">{{ include('users/users_show/users_show_activities.html.twig') }}</div>
                    {% if app.user and app.user.id == user.id %}
                        <div id="page3" class="col s12">{{ include('users/users_show/users_show_edit.html.twig') }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/users_show/users_show_infos.html.twig
<div class="container">
    <p class="justify">{{ user.utiBiographie }}</p>
    <ul>
        <li><strong>Age : </strong> {{ user.utiNaissance ? user.utiNaissance.diff(date('now'|date())).y : '???' }} ans</li>
        <li><strong>Dernière connexion : </strong> {{ user.utiDerniereSessionString }}</li>
        <li><strong>Inscription : </strong> {{ user.utiInscriptionString }}</li>
    </ul>
</div>